import React, { useState, useRef } from "react";
import ChatWidget from './chatWidget'
// TODO the uncommented code is generated by GPT
// TODO try to study the code by GPT 
// This defines typescript type for props; what you pass into ChatInput component

//const textareaRef = useRef<HTMLTextAreaElement>(null);
/*type ChatInputProps = {

    onSend?: (text: string) => void; //Type must be a function that takes a str and returns void or str
    placeholder?: string;
    text?:string;
};
 function ChatInputIo({
        
    onSend = (text) => console.log(text) // Replace it with a django send api function 
    }: ChatInputProps){

}*/

type ChatInputProps = {
    onSend?: (text: string) => void;
    placeholder?: string;
};

export default function ChatInput({
    onSend = (text) => undefined,
    placeholder = "",
}: ChatInputProps) {
  const [text, setText] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const handleSend = () => {
    const trimmed = text.trim();
    if (!trimmed) return;
    onSend(trimmed);
    // Here probably handle Django request 
    console.log(trimmed)
    setText(trimmed);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="w-full p-3 bg-transparent">
      <div className="max-w-3xl mx-auto flex items-end gap-3">
        <div className="flex-1 relative">
          <textarea
            ref={textareaRef}
            value={text}
            onChange={(e) => setText(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={placeholder}
            rows={1}
            className="
              w-full resize-none overflow-hidden 
              bg-white/95 text-gray-900 
              border border-gray-300 rounded-2xl 
              focus:border-blue-400 focus:ring-0 
              py-2 pl-3 pr-12 text-sm leading-relaxed outline-none
              placeholder-gray-500
            "
          />
          <button
            onClick={handleSend}
            disabled={!text.trim()}
          >
            <ChatWidget/>
          </button>
        </div>
      </div>
    </div>
  );
}


    
    

